---
name: "TheIntroDB"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Adds skip segments for intros, recaps, credits, and previews from TheIntroDB's API."
description: >
  Adds skip segments for intros, recaps, credits, and previews from TheIntroDB's API.
category: "General"
owner: "TheIntroDB"
artifacts:
- "TheIntroDB.dll"
changelog: >
  changelog
